# Generated by Django 4.2.1 on 2023-05-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modified_user',
            name='first name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='modified_user',
            name='last name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modified_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
