# Generated by Django 4.2.1 on 2023-05-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_modified_user_first_name_modified_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modified_user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='modified_user',
            name='first name',
            field=models.CharField(max_length=50),
        ),
    ]
