# Generated by Django 4.2.1 on 2023-05-20 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_modified_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='stars',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
