# Generated by Django 4.2.1 on 2023-05-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_about_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='discription',
            field=models.CharField(max_length=1000),
        ),
    ]
