# Generated by Django 4.2.1 on 2023-05-20 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_about_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='stars',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
