# Generated by Django 4.2.1 on 2023-05-20 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_skill_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acadmic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=500)),
                ('class', models.CharField(max_length=500)),
                ('passed_year', models.IntegerField()),
                ('marks', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('working_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=500)),
                ('role', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=500)),
                ('completeness', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='modified_user',
            name='skill',
            field=models.ManyToManyField(to='main.skill', verbose_name='skill'),
        ),
        migrations.AddField(
            model_name='modified_user',
            name='academic',
            field=models.ManyToManyField(to='main.academic', verbose_name='academic'),
        ),
        migrations.AddField(
            model_name='modified_user',
            name='academic_project',
            field=models.ManyToManyField(to='main.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='modified_user',
            name='education',
            field=models.ManyToManyField(to='main.education', verbose_name='education'),
        ),
        migrations.AddField(
            model_name='modified_user',
            name='internships',
            field=models.ManyToManyField(to='main.internships', verbose_name='internships'),
        ),
        migrations.AddField(
            model_name='modified_user',
            name='links',
            field=models.ManyToManyField(to='main.links', verbose_name='link'),
        ),
        migrations.AddField(
            model_name='modified_user',
            name='position',
            field=models.ManyToManyField(to='main.position', verbose_name='position'),
        ),
    ]
