# Generated by Django 4.2.1 on 2023-05-20 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_modified_user_academic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='passed_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1995), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
