# Generated by Django 4.2.1 on 2023-05-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_education_passed_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name_plural': 'Links'},
        ),
    ]
