# Generated by Django 4.2.1 on 2023-05-21 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_first_name_modified_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='class',
            new_name='classes',
        ),
    ]
