# Generated by Django 4.2.1 on 2023-05-21 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_class_education_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='passed_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1995), django.core.validators.MaxValueValidator(2028)]),
        ),
    ]
