# Generated by Django 4.2.1 on 2023-05-21 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_education_passed_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internships',
            options={'verbose_name_plural': 'Internships'},
        ),
        migrations.AlterField(
            model_name='internships',
            name='working_year',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
