# Generated by Django 4.2.1 on 2023-05-23 04:06

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_modified_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modified_user',
            name='profile',
            field=models.ImageField(blank=True, upload_to=main.models.user_profile_upload_path),
        ),
    ]
